apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-web
  labels:
    app: fin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-web
  template:
    metadata:
      labels:
        app: fin-web
    spec:
      containers:
      - name: fin-web
        image: DOCKER_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5173
          name: web
        - containerPort: 3001
          name: mock
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
