apiVersion: v1
kind: Service
metadata:
  name: fin-web-service
spec:
  type: NodePort
  selector:
    app: fin-web
  ports:
    - name: web
      protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30173 # WEB_PORT
    - name: mock
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001 # MOCK_PORT
